[[redirects]]
  from = '/*'
  to = 'https://www.kamla.xyz/:splat'
  status = 200
  [headers.values]
    Access-Control-Allow-Origin = "*"
[[redirects]]
  from = '/*'
  to = '/index.html'
  status = 200
